micronaut:
  application:
    name: clientService

    #datasources:
    #  default:
    #    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #    username: sa
    #    password: ""
    #    driverClassName: org.h2.Driver


datasources:
  default:
    url: jdbc:mysql://database-1.cbklyngfktu5.us-east-2.rds.amazonaws.com:3306/cliente-db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: admin
    password: 12345678
    driverClassName: "com.mysql.cj.jdbc.Driver"
    dialect: MYSQL
jpa:
  default:
    packages-to-scan:
      - 'br.com.curso.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true